name: text_painter_demo
description: "Text versus TextPainter"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

flutter:
  uses-material-design: true

dependencies:
  event_bus: 2.0.0
  flutter:
    sdk: flutter
